<?php
// http://www.jokes4us.com/animaljokes/catjokes.html
$jokes = [
  [ 'question' => 'How do you know when your cat\'s done cleaning herself?',  'answer' => 'She\'s smoking a cigarette.' ],
  [ 'question' => 'What is it called when a cat wins a dog show?',  'answer' => 'A CAT-HAS-TROPHY!' ],
  [ 'question' => 'What do you get if you cross a leopard with a watchdog?',  'answer' => 'A terrified postman!' ],
  [ 'question' => 'What do you call a pile of kittens?',  'answer' => 'a meowntain' ],
  [ 'question' => 'When is a lion not a lion?',  'answer' => 'When he turns into his cage!' ],
  [ 'question' => 'Why don\'t cats like online shopping?',  'answer' => 'They prefer a cat-alogue.' ],
  [ 'question' => 'What do you call a flying cat?',  'answer' => 'I\'m-paws-sible.' ],
  [ 'question' => 'What did the cat say when he lost all his money?',  'answer' => 'I\'m paw!' ],
  [ 'question' => 'Did you hear about the cat who swallowed a ball of yarn?',  'answer' => 'She had a litter of mittens.' ],
  [ 'question' => 'What do you call a lion who has eaten your mother\'s sister?',  'answer' => 'An aunt-eater!' ],
  [ 'question' => 'Who are cats going to vote for in November?',  'answer' => 'Hillary Kitten.' ],
  [ 'question' => 'Why shouldn\'t you kidnap the kitten, Keanu?',  'answer' => 'Because curiousity killed the cat burglar.' ],
  [ 'question' => 'What do you get if you cross a cat with a dark horse?',  'answer' => 'Kitty Perry' ],
  [ 'question' => 'What do you call a cat in a station wagon?',  'answer' => 'A car-pet' ],
  [ 'question' => 'What do tigers wear in bed?',  'answer' => 'Stripey pyjamas!' ],
  [ 'question' => 'Why did the cat wear a dress?',  'answer' => 'She was feline fine.' ],
  [ 'question' => 'What do you call the cat that was caught by the police?',  'answer' => 'The purrpatrator.' ],
  [ 'question' => 'How do you get a wet pussy?',  'answer' => 'Put it in the shower.' ],
  [ 'question' => 'Why did the cat put the letter "M" into the fridge?',  'answer' => 'Because it turns "ice" into "mice"!' ],
  [ 'question' => 'What is smarter than a talking cat?',  'answer' => 'A spelling bee!' ],
  [ 'question' => 'Why was the cat sitting on the computer?',  'answer' => 'To keep an eye on the mouse!' ],
  [ 'question' => 'What is the most breathless thing on television?',  'answer' => 'The Pink Panter Show!' ],
  [ 'question' => 'What did the cat say when he lost his toys?',  'answer' => 'You got to be kitten me.' ],
  [ 'question' => 'What is a cat\'s favorite color?',  'answer' => 'Purrrple!' ],
  [ 'question' => 'What do you get if you cross a tiger with a kangeroo?',  'answer' => 'A stripey jumper!' ],
  [ 'question' => 'What do you get if you cross a chick with an alley cat?',  'answer' => 'A peeping tom.' ],
  [ 'question' => 'What did the alien say to the cat?',  'answer' => 'Take me to your litter.' ],
  [ 'question' => 'What do you get if you cross a cat with a bottle of vinegar?',  'answer' => 'A sourpuss!' ],
  [ 'question' => 'How are tigers like sergeants in the army?',  'answer' => 'They both wear stripes!' ],
  [ 'question' => 'What do you get if you cross a tiger with a sheep?',  'answer' => 'A stripey sweater!' ],
  [ 'question' => 'Why is the desert lion everyone\'s favorite at Christmas?',  'answer' => 'Because he has sandy claws!' ],
  [ 'question' => 'How does a lion greet the other animals in the field?',  'answer' => '\'Pleased to eat you.\'!' ],
  [ 'question' => 'Do you want to hear a bad cat joke?',  'answer' => 'Just kitten.' ],
  [ 'question' => 'What do you get if you cross a tiger with a snowman?',  'answer' => 'Frostbite!' ],
  [ 'question' => 'What is a French cat\'s favorite pudding?',  'answer' => 'Chocolate mousse!' ],
  [ 'question' => 'What looks like half a cat?',  'answer' => 'The other half!' ],
  [ 'question' => 'What was the name of the film about a killer lion that swam underwater?',  'answer' => '\'Claws.\'' ],
  [ 'question' => 'If a four-legged animal is a quadruped and a two-legged animal is a biped, What\'s a tiger?',  'answer' => 'A stri-ped!' ],
  [ 'question' => 'What do you get if you cross a tiger with a sheep?',  'answer' => 'A stripey sweater!' ],
  [ 'question' => 'What do you call a cat that wears make up?',  'answer' => 'Glamourpuss.' ],
  [ 'question' => 'What do cats like to read?',  'answer' => 'Cat-alogues!' ],
  [ 'question' => 'What kind of sports car does a cat drive?',  'answer' => 'A Furrari.' ],
  [ 'question' => 'How does a lion greet the other animals in the field?',  'answer' => '\'Pleased to eat you.\'!' ],
  [ 'question' => 'What do you get if you cross a tiger with a snowman?',  'answer' => 'Frostbite!' ],
  [ 'question' => 'What do you get when you take a Kitty Kat to the tailor?',  'answer' => 'Bad Blood.' ],
  [ 'question' => 'What do you call a cat that gets anything it wants?',  'answer' => 'Purrr-suasive.' ],
  [ 'question' => 'What do you call a cat who just ate a duck?',  'answer' => 'a duck-filled platy puss.' ],
  [ 'question' => 'What did the lions say to his cubs when he taught them to hunt?',  'answer' => '\'Don\'t go over the road till you see the zebra crossing.\'' ],
  [ 'question' => 'What is lion\'s favorite food?',  'answer' => 'Baked beings!' ],
  [ 'question' => 'What happened when the lion ate the comedian?',  'answer' => 'He felt funny!' ],
  [ 'question' => 'What\'s striped and bouncy?',  'answer' => 'A tiger on a pogo stick!' ],
  [ 'question' => 'What is the cat\'s favorite TV show?',  'answer' => 'The evening mews!' ],
  [ 'question' => 'How can you get a set of teeth put in for free?',  'answer' => 'Smack a lion!' ],
  [ 'question' => 'What is a cat\'s favorite dance move?',  'answer' => 'The Purr-colator.' ],
  [ 'question' => 'Why was the cat scared of the tree?',  'answer' => 'Because of its bark.' ],
  [ 'question' => 'What do you feed an invisible cat?',  'answer' => 'Evaporated milk.' ],
  [ 'question' => 'What\'s worse than raining cats and dogs?',  'answer' => 'Hailing taxi cabs!' ],
  [ 'question' => 'How is cat food sold?',  'answer' => 'Usually purr can!' ],
  [ 'question' => 'What flies around your light at night and can bite off your head?',  'answer' => 'A tiger moth!' ],
  [ 'question' => 'What does the lion say to his friends before they go out hunting for food?',  'answer' => '\'Let us prey.\'' ],
  [ 'question' => 'What\'s the unluckiest kind of cat to have?',  'answer' => 'A catastrophe!' ],
  [ 'question' => 'Who was the most powerful cat in China?',  'answer' => 'Chairman Miaow!' ],
  [ 'question' => 'What do you get if you cross a cat with a tree?',  'answer' => 'A cat-a-logue!' ],
  [ 'question' => 'What do you call a cat race?',  'answer' => 'A meowathon.' ],
  [ 'question' => 'Why did the cat get pulled over by the police?',  'answer' => 'Because it "littered"' ],
  [ 'question' => 'What do you call a cat with eight legs that likes to swim?',  'answer' => 'An octopuss!' ],
  [ 'question' => 'Why did the cat join the Red Cross?',  'answer' => 'Because she wanted to be a first-aid kit!' ],
  [ 'question' => 'When the cat\'s away.....?',  'answer' => 'The house smells better!' ],
  [ 'question' => 'What is a cats favorite vegetable?',  'answer' => 'As-purr-agus.' ],
  [ 'question' => 'Did you know that cats designed the great pyramids of Giza?',  'answer' => 'It was all drawn out on paw-pyrus.' ],
  [ 'question' => 'What\'s the difference between a cat and a frog?',  'answer' => 'A Cat has nine lives but a Frog croaks every night!' ],
  [ 'question' => 'Did you hear about the passenger who had to be escorted off the airplane?',  'answer' => 'She let the cat out of the bag.' ],
  [ 'question' => 'Why are cats so good at video games?',  'answer' => 'Because they have nine lives!' ],
  [ 'question' => 'What\'s a cat\'s favorite button on the tv remote?',  'answer' => 'Paws' ],
  [ 'question' => 'Did you hear about the cat that thought she was a dog?',  'answer' => 'She was purr-plexed.' ],
  [ 'question' => 'What do cats like to eat on sunny days?',  'answer' => 'Mice cream cones!' ],
  [ 'question' => 'What do you call a cat that doesn\'t use the litter box?',  'answer' => 'A pet project.' ],
  [ 'question' => 'What do you get if you cross a cat with Father Christmas?',  'answer' => 'Santa Claws!' ],
  [ 'question' => 'What kind of car does a fat cat drive?',  'answer' => 'a Catillac!' ],
  [ 'question' => 'Why was the cat so small?',  'answer' => 'Because it only ate condensed milk!' ],
  [ 'question' => 'What do you call Long John Silver when he has a cat on his shoulder?',  'answer' => 'A purr-ate!' ],
  [ 'question' => 'What do you call a cat that smells good?',  'answer' => 'prrrr-fume.' ],
  [ 'question' => 'Did you hear about the cat who wanted to learn how to bark?',  'answer' => 'Curiousity killed the cat.' ],
  [ 'question' => 'How do the Vietnamese like their soup?',  'answer' => 'Purrrrrfect.' ],
  [ 'question' => 'What is a cats favorite kitchen tool?',  'answer' => 'The "whisker".' ],
  [ 'question' => 'What do you call a cat that lives in an igloo?',  'answer' => 'An eskimew!' ],
  [ 'question' => 'What is a cats favorite book?',  'answer' => 'The prince and the paw-purr.' ],
  [ 'question' => 'What did the cat say to the dog?',  'answer' => 'Check meow-t!' ],
  [ 'question' => 'What do you call a cat on ice?',  'answer' => 'One cool cat. Cat: "You\'re not real!" Nyan Cat: "At least I have a sparkly rainbow butt."' ],
  [ 'question' => 'What is a cats favorite musical instrument?',  'answer' => 'Purr-cussion.' ],
  [ 'question' => 'What do you call a cat that can address the media?',  'answer' => 'a Press Kit.' ],
  [ 'question' => 'What do cats wear at night?',  'answer' => 'paw-jamas!' ],
  [ 'question' => 'What time is it when ten cats chase a mouse?',  'answer' => 'Ten After One.' ],
  [ 'question' => 'What do you call a cat that does tricks?',  'answer' => 'A magic kit.' ],
  [ 'question' => 'What do you call a painting of a cat?',  'answer' => 'A paw-trait' ],
  [ 'question' => 'What do you call a cat when it is huge?',  'answer' => 'A MEOW-SIVE CAT' ],
  [ 'question' => 'What do you call a cat that can\'t stop licking itself?',  'answer' => 'Purrr-verted.' ],
  [ 'question' => 'What do you call a cat that can put together furniture from Ikea?',  'answer' => 'an Assembly kit.' ],
  [ 'question' => 'Why did the cat go to the river?',  'answer' => 'Claws it wanted to.' ],
  [ 'question' => 'What\'s grumpy cat\'s favourite ride at Dreamworld in Australia?',  'answer' => 'The Paw!' ],
  [ 'question' => 'What\'s the first thing you say to a cat?',  'answer' => 'HELLO KITTY!' ],
  [ 'question' => 'What do you need to get a fast cat to use the litter box?',  'answer' => 'Quicksand.' ],
  [ 'question' => 'What was the special offer at the pet store this week?',  'answer' => 'Buy 1 Cat get 1 Flea!' ],
  [ 'question' => 'What does a cat say when somebody steps on its tail?',  'answer' => 'Me-ow!' ],
  [ 'question' => 'How do you make cats furry?',  'answer' => 'The spin cycle.' ],
  [ 'question' => 'Did you hear about the cat that climbed the Himilayas?',  'answer' => 'She was a sher-paw.' ],
  [ 'question' => 'Why did the cat cross the road?',  'answer' => 'It was the chicken\'s day off!' ],
  [ 'question' => 'Where does a cat go when he looses his tail?',  'answer' => 'The retail store!' ],
  [ 'question' => 'What do you call a cat that can rough the great outdoors?',  'answer' => 'A survival kit.' ],
  [ 'question' => 'What do you call a cat on the beach at Christmas time?',  'answer' => 'Sandy Claws!' ]
];

$joke = $jokes[array_rand($jokes)];

$output  = 'Q: ' . $joke['question'] . PHP_EOL;
$output .= 'A: ' . $joke['answer'];

apache_setenv('no-gzip', '1');
echo str_pad($output, 127 /* longest cat joke */, PHP_EOL);
